export const countries = {
  AF: {
    locales: {
      en: "Afghanistan",
      fr: "Afghanistan",
      sp: "Afganistán",
      ge: "Afghanistan",
      de: "Afghanistan",
    },
    alpha3: "AFG",
    countryCode: "4",
    label: "AF - Afghanistan",
  },
  AX: {
    locales: {
      en: "Åland Islands",
      fr: "Åland, Iles",
      sp: "Islas Åland",
      ge: "Åland Inseln",
      de: "Åland, Islands",
    },
    alpha3: "ALA",
    countryCode: "248",
    label: "AX - Åland Islands",
  },
  AL: {
    locales: {
      en: "Albania",
      fr: "Albanie",
      sp: "Albania",
      ge: "Albanien",
      de: "Albania",
    },
    alpha3: "ALB",
    countryCode: "8",
    label: "AL - Albania",
  },
  DZ: {
    locales: {
      en: "Algeria",
      fr: "Algérie",
      sp: "Argelia",
      ge: "Algerien",
      de: "Algeria",
    },
    alpha3: "DZA",
    countryCode: "12",
    label: "DZ - Algeria",
  },
  AS: {
    locales: {
      en: "American Samoa",
      fr: "Samoa américaines",
      sp: "Samoa Americana",
      ge: "Amerikanisch-Samoa",
      de: "American Samoa",
    },
    alpha3: "ASM",
    countryCode: "16",
    label: "AS - American Samoa",
  },
  AD: {
    locales: {
      en: "Andorra",
      fr: "Andorre",
      sp: "Andorra",
      ge: "Andorra",
      de: "Andorra",
    },
    alpha3: "AND",
    countryCode: "20",
    label: "AD - Andorra",
  },
  AO: {
    locales: {
      en: "Angola",
      fr: "Angola",
      sp: "Angola",
      ge: "Angola",
      de: "Angola",
    },
    alpha3: "AGO",
    countryCode: "24",
    label: "AO - Angola",
  },
  AI: {
    locales: {
      en: "Anguilla",
      fr: "Anguilla",
      sp: "Anguila",
      ge: "Anguilla",
      de: "Anguilla",
    },
    alpha3: "AIA",
    countryCode: "660",
    label: "AI - Anguilla",
  },
  AQ: {
    locales: {
      en: "Antarctica",
      fr: "Antarctique",
      sp: "Antártida",
      ge: "Antarktis",
      de: "Antarctica",
    },
    alpha3: "ATA",
    countryCode: "10",
    label: "AQ - Antarctica",
  },
  AG: {
    locales: {
      en: "Antigua and Barbuda",
      fr: "Antigua-et-Barbuda",
      sp: "Antigua y Barbuda",
      ge: "Antigua und Barbuda",
      de: "Antigua and Barbuda",
    },
    alpha3: "ATG",
    countryCode: "28",
    label: "AG - Antigua and Barbuda",
  },
  AR: {
    locales: {
      en: "Argentina",
      fr: "Argentine",
      sp: "Argentina",
      ge: "Argentinien",
      de: "Argentina",
    },
    alpha3: "ARG",
    countryCode: "32",
    label: "AR - Argentina",
  },
  AM: {
    locales: {
      en: "Armenia",
      fr: "Arménie",
      sp: "Armenia",
      ge: "Armenien",
      de: "Armenia",
    },
    alpha3: "ARM",
    countryCode: "51",
    label: "AM - Armenia",
  },
  AW: {
    locales: {
      en: "Aruba",
      fr: "Aruba",
      sp: "Aruba",
      ge: "Aruba",
      de: "Aruba",
    },
    alpha3: "ABW",
    countryCode: "533",
    label: "AW - Aruba",
  },
  AU: {
    locales: {
      en: "Australia",
      fr: "Australie",
      sp: "Australia",
      ge: "Australien",
      de: "Australia",
    },
    alpha3: "AUS",
    countryCode: "36",
    label: "AU - Australia",
  },
  AT: {
    locales: {
      en: "Austria",
      fr: "Autriche",
      sp: "Austria",
      ge: "Österreich",
      de: "Austria",
    },
    alpha3: "AUT",
    countryCode: "40",
    label: "AT - Austria",
  },
  AZ: {
    locales: {
      en: "Azerbaijan",
      fr: "Azerbaïdjan",
      sp: "Azerbaiyán",
      ge: "Aserbaidschan",
      de: "Azerbaijan",
    },
    alpha3: "AZE",
    countryCode: "31",
    label: "AZ - Azerbaijan",
  },
  BS: {
    locales: {
      en: "Bahamas",
      fr: "Bahamas",
      sp: "Bahamas",
      ge: "Bahamas",
      de: "Bahamas",
    },
    alpha3: "BHS",
    countryCode: "44",
    label: "BS - Bahamas",
  },
  BH: {
    locales: {
      en: "Bahrain",
      fr: "Bahreïn",
      sp: "Bahrein",
      ge: "Bahrain",
      de: "Bahrain",
    },
    alpha3: "BHR",
    countryCode: "48",
    label: "BH - Bahrain",
  },
  BD: {
    locales: {
      en: "Bangladesh",
      fr: "Bangladesh",
      sp: "Bangladesh",
      ge: "Bangladesch",
      de: "Bangladesh",
    },
    alpha3: "BGD",
    countryCode: "50",
    label: "BD - Bangladesh",
  },
  BB: {
    locales: {
      en: "Barbados",
      fr: "Barbade",
      sp: "Barbados",
      ge: "Barbados",
      de: "Barbados",
    },
    alpha3: "BRB",
    countryCode: "52",
    label: "BB - Barbados",
  },
  BY: {
    locales: {
      en: "Belarus",
      fr: "Biélorussie",
      sp: "Bielorrusia",
      ge: "Belarus",
      de: "Belarus",
    },
    alpha3: "BLR",
    countryCode: "112",
    label: "BY - Belarus",
  },
  BE: {
    locales: {
      en: "Belgium",
      fr: "Belgique",
      sp: "Bélgica",
      ge: "Belgien",
      de: "Belgium",
    },
    alpha3: "BEL",
    countryCode: "56",
    label: "BE - Belgium",
  },
  BZ: {
    locales: {
      en: "Belize",
      fr: "Belize",
      sp: "Belice",
      ge: "Belize",
      de: "Belize",
    },
    alpha3: "BLZ",
    countryCode: "84",
    label: "BZ - Belize",
  },
  BJ: {
    locales: {
      en: "Benin",
      fr: "Bénin",
      sp: "Benín",
      ge: "Benin",
      de: "Benin",
    },
    alpha3: "BEN",
    countryCode: "204",
    label: "BJ - Benin",
  },
  BM: {
    locales: {
      en: "Bermuda",
      fr: "Bermudes",
      sp: "Bermudas",
      ge: "Bermuda",
      de: "Bermuda",
    },
    alpha3: "BMU",
    countryCode: "60",
    label: "BM - Bermuda",
  },
  BT: {
    locales: {
      en: "Bhutan",
      fr: "Bhoutan",
      sp: "Bután",
      ge: "Bhutan",
      de: "Bhutan",
    },
    alpha3: "BTN",
    countryCode: "64",
    label: "BT - Bhutan",
  },
  BO: {
    locales: {
      en: "Bolivia (Plurinational State of)",
      fr: "Bolivie",
      sp: "Bolivia",
      ge: "Bolivien",
      de: "Bolivia",
    },
    alpha3: "BOL",
    countryCode: "68",
    label: "BO - Bolivia (Plurinational State of)",
  },
  BQ: {
    locales: {
      en: "Bonaire, Sint Eustatius and Saba",
      fr: "Bonaire, Saint-Eustache et Saba",
      sp: "Bonaire, San Eustaquio y Saba",
      ge: "Bonaire, St. Eustatius und Saba",
      de: "Bonaire, St Eustatius and Saba",
    },
    alpha3: "BES",
    countryCode: "535",
    label: "BQ - Bonaire, Sint Eustatius and Saba",
  },
  BA: {
    locales: {
      en: "Bosnia and Herzegovina",
      fr: "Bosnie-Herzégovine",
      sp: "Bosnia y Herzegovina",
      ge: "Bosnien und Herzegowina",
      de: "Bosnia and Herzegovina",
    },
    alpha3: "BIH",
    countryCode: "70",
    label: "BA - Bosnia and Herzegovina",
  },
  BW: {
    locales: {
      en: "Botswana",
      fr: "Botswana",
      sp: "Botswana",
      ge: "Botsuana",
      de: "Botswana",
    },
    alpha3: "BWA",
    countryCode: "72",
    label: "BW - Botswana",
  },
  BV: {
    locales: {
      en: "Bouvet Island",
      fr: "Bouvet, Ile",
      sp: "Isla de Bouvet",
      ge: "Bouvet Insel",
      de: "Bouvet Island",
    },
    alpha3: "BVT",
    countryCode: "74",
    label: "BV - Bouvet Island",
  },
  BR: {
    locales: {
      en: "Brazil",
      fr: "Brésil",
      sp: "Brasil",
      ge: "Brasilien",
      de: "Brazil",
    },
    alpha3: "BRA",
    countryCode: "76",
    label: "BR - Brazil",
  },
  IO: {
    locales: {
      en: "British Indian Ocean Territory",
      fr: "Océan Indien, Territoire britannique de l'",
      sp: "Océano Índico, Territorio Británico del",
      ge: "Britisches Territorium im Indischen Ozean",
      de: "Indian Ocean, British Territory of the",
    },
    alpha3: "IOT",
    countryCode: "86",
    label: "IO - British Indian Ocean Territory",
  },
  BN: {
    locales: {
      en: "Brunei Darussalam",
      fr: "Brunéi Darussalam",
      sp: "Brunei Darussalam",
      ge: "Brunei Darussalam",
      de: "Brunei Darussalam",
    },
    alpha3: "BRN",
    countryCode: "96",
    label: "BN - Brunei Darussalam",
  },
  BG: {
    locales: {
      en: "Bulgaria",
      fr: "Bulgarie",
      sp: "Bulgaria",
      ge: "Bulgarien",
      de: "Bulgaria",
    },
    alpha3: "BGR",
    countryCode: "100",
    label: "BG - Bulgaria",
  },
  BF: {
    locales: {
      en: "Burkina Faso",
      fr: "Burkina Faso",
      sp: "Burkina Faso",
      ge: "Burkina Faso",
      de: "Burkina Faso",
    },
    alpha3: "BFA",
    countryCode: "854",
    label: "BF - Burkina Faso",
  },
  BI: {
    locales: {
      en: "Burundi",
      fr: "Burundi",
      sp: "Burundi",
      ge: "Burundi",
      de: "Burundi",
    },
    alpha3: "BDI",
    countryCode: "108",
    label: "BI - Burundi",
  },
  CV: {
    locales: {
      en: "Cabo Verde",
      fr: "Cap-Vert",
      sp: "Cabo Verde",
      ge: "Cabo Verde",
      de: "Cabo Verde",
    },
    alpha3: "CPV",
    countryCode: "132",
    label: "CV - Cabo Verde",
  },
  KH: {
    locales: {
      en: "Cambodia",
      fr: "Cambodge",
      sp: "Camboya",
      ge: "Kambodscha",
      de: "Cambodia",
    },
    alpha3: "KHM",
    countryCode: "116",
    label: "KH - Cambodia",
  },
  CM: {
    locales: {
      en: "Cameroon",
      fr: "Cameroune",
      sp: "Camerún",
      ge: "Kamerun",
      de: "Cameroon",
    },
    alpha3: "CMR",
    countryCode: "120",
    label: "CM - Cameroon",
  },
  CA: {
    locales: {
      en: "Canada",
      fr: "Canada",
      sp: "Canadá",
      ge: "Kanada",
      de: "Canada",
    },
    alpha3: "CAN",
    countryCode: "124",
    label: "CA - Canada",
  },
  KY: {
    locales: {
      en: "Cayman Islands",
      fr: "Caïman, Iles",
      sp: "Islas Caimán",
      ge: "Kaimaninseln",
      de: "Cayman Islands",
    },
    alpha3: "CYM",
    countryCode: "136",
    label: "KY - Cayman Islands",
  },
  CF: {
    locales: {
      en: "Central African Republic",
      fr: "République centrafricaine",
      sp: "República Centroafricana",
      ge: "Zentralafrikanische Republik",
      de: "Central African Republic",
    },
    alpha3: "CAF",
    countryCode: "140",
    label: "CF - Central African Republic",
  },
  TD: {
    locales: {
      en: "Chad",
      fr: "Tchad",
      sp: "Chad",
      ge: "Tschad",
      de: "Chad",
    },
    alpha3: "TCD",
    countryCode: "148",
    label: "TD - Chad",
  },
  CL: {
    locales: {
      en: "Chile",
      fr: "Chili",
      sp: "Chile",
      ge: "Chile",
      de: "Chile",
    },
    alpha3: "CHL",
    countryCode: "152",
    label: "CL - Chile",
  },
  CN: {
    locales: {
      en: "China",
      fr: "Chine",
      sp: "China",
      ge: "China",
      de: "China",
    },
    alpha3: "CHN",
    countryCode: "156",
    label: "CN - China",
  },
  CX: {
    locales: {
      en: "Christmas Island",
      fr: "Christmas, Ile",
      sp: "Isla de Navidad",
      ge: "Christmas Insel",
      de: "Christmas Island",
    },
    alpha3: "CXR",
    countryCode: "162",
    label: "CX - Christmas Island",
  },
  CC: {
    locales: {
      en: "Cocos (Keeling) Islands",
      fr: "Cocos (Keeling), Iles",
      sp: "Islas Cocos (Keeling)",
      ge: "Cocos (Keeling) Inseln",
      de: "Cocos (Keeling) Islands",
    },
    alpha3: "CCK",
    countryCode: "166",
    label: "CC - Cocos (Keeling) Islands",
  },
  CO: {
    locales: {
      en: "Colombia",
      fr: "Colombie",
      sp: "Colombia",
      ge: "Kolumbien",
      de: "Colombia",
    },
    alpha3: "COL",
    countryCode: "170",
    label: "CO - Colombia",
  },
  KM: {
    locales: {
      en: "Comoros",
      fr: "Comores",
      sp: "Comoras",
      ge: "Komoren",
      de: "Comoros",
    },
    alpha3: "COM",
    countryCode: "174",
    label: "KM - Comoros",
  },
  CG: {
    locales: {
      en: "Congo",
      fr: "Congo",
      sp: "Congo",
      ge: "Kongo",
      de: "Congo",
    },
    alpha3: "COG",
    countryCode: "178",
    label: "CG - Congo",
  },
  CD: {
    locales: {
      en: "Congo, Democratic Republic of the",
      fr: "République démocratique du Congo",
      sp: "República Democrática del Congo",
      ge: "Demokratische Republik Kongo",
      de: "Democratic Republic of the Congo",
    },
    alpha3: "COD",
    countryCode: "180",
    label: "CD - Congo, Democratic Republic of the",
  },
  CK: {
    locales: {
      en: "Cook Islands",
      fr: "Cook, Iles",
      sp: "Islas Cook",
      ge: "Cook-Inseln",
      de: "Cook Islands",
    },
    alpha3: "COK",
    countryCode: "184",
    label: "CK - Cook Islands",
  },
  CR: {
    locales: {
      en: "Costa Rica",
      fr: "Costa Rica",
      sp: "Costa Rica",
      ge: "Costa Rica",
      de: "Costa Rica",
    },
    alpha3: "CRI",
    countryCode: "188",
    label: "CR - Costa Rica",
  },
  CI: {
    locales: {
      en: "Côte d'Ivoire",
      fr: "Cote d'Ivoire",
      sp: "Costa de Marfil",
      ge: "Elfenbeinküste",
      de: "Ivory Coast",
    },
    alpha3: "CIV",
    countryCode: "384",
    label: "CI - Côte d'Ivoire",
  },
  HR: {
    locales: {
      en: "Croatia",
      fr: "Coatie",
      sp: "Croacia",
      ge: "Kroatien",
      de: "Croatia",
    },
    alpha3: "HRV",
    countryCode: "191",
    label: "HR - Croatia",
  },
  CU: {
    locales: {
      en: "Cuba",
      fr: "Cuba",
      sp: "Cuba",
      ge: "Kuba",
      de: "Cuba",
    },
    alpha3: "CUB",
    countryCode: "192",
    label: "CU - Cuba",
  },
  CW: {
    locales: {
      en: "Curaçao",
      fr: "Curaçao",
      sp: "Curaçao",
      ge: "Curaçao",
      de: "Curaçao",
    },
    alpha3: "CUW",
    countryCode: "531",
    label: "CW - Curaçao",
  },
  CY: {
    locales: {
      en: "Cyprus",
      fr: "Chypre",
      sp: "Chipre",
      ge: "Zypern",
      de: "Cyprus",
    },
    alpha3: "CYP",
    countryCode: "196",
    label: "CY - Cyprus",
  },
  CZ: {
    locales: {
      en: "Czechia",
      fr: "République tchèque",
      sp: "República Checa",
      ge: "Tschechische Republik",
      de: "Czechia",
    },
    alpha3: "CZE",
    countryCode: "203",
    label: "CZ - Czechia",
  },
  DK: {
    locales: {
      en: "Denmark",
      fr: "Danemark",
      sp: "Dinamarca",
      ge: "Dänemark",
      de: "Denmark",
    },
    alpha3: "DNK",
    countryCode: "208",
    label: "DK - Denmark",
  },
  DJ: {
    locales: {
      en: "Djibouti",
      fr: "Djibouti",
      sp: "Yibuti",
      ge: "Dschibuti",
      de: "Djibouti",
    },
    alpha3: "DJI",
    countryCode: "262",
    label: "DJ - Djibouti",
  },
  DM: {
    locales: {
      en: "Dominica",
      fr: "Dominique",
      sp: "Dominica",
      ge: "Dominica",
      de: "Dominica",
    },
    alpha3: "DMA",
    countryCode: "212",
    label: "DM - Dominica",
  },
  DO: {
    locales: {
      en: "Dominican Republic",
      fr: "République dominicaine",
      sp: "República Dominicana",
      ge: "Dominikanische Republik",
      de: "Dominican Republic",
    },
    alpha3: "DOM",
    countryCode: "214",
    label: "DO - Dominican Republic",
  },
  EC: {
    locales: {
      en: "Ecuador",
      fr: "Équateur",
      sp: "Ecuador",
      ge: "Ecuador",
      de: "Ecuador",
    },
    alpha3: "ECU",
    countryCode: "218",
    label: "EC - Ecuador",
  },
  EG: {
    locales: {
      en: "Egypt",
      fr: "Égypte",
      sp: "Egipto",
      ge: "Ägypten",
      de: "Egypt",
    },
    alpha3: "EGY",
    countryCode: "818",
    label: "EG - Egypt",
  },
  SV: {
    locales: {
      en: "El Salvador",
      fr: "Salvador",
      sp: "El Salvador",
      ge: "El Salvador",
      de: "El Salvador",
    },
    alpha3: "SLV",
    countryCode: "222",
    label: "SV - El Salvador",
  },
  GQ: {
    locales: {
      en: "Equatorial Guinea",
      fr: "Guinée Équatoriale",
      sp: "Guinea Ecuatorial",
      ge: "Äquatorialguinea",
      de: "Equatorial Guinea",
    },
    alpha3: "GNQ",
    countryCode: "226",
    label: "GQ - Equatorial Guinea",
  },
  ER: {
    locales: {
      en: "Eritrea",
      fr: "Érythrée",
      sp: "Eritrea",
      ge: "Eritrea",
      de: "Eritrea",
    },
    alpha3: "ERI",
    countryCode: "232",
    label: "ER - Eritrea",
  },
  EE: {
    locales: {
      en: "Estonia",
      fr: "Estonie",
      sp: "Estonia",
      ge: "Estland",
      de: "Estonia",
    },
    alpha3: "EST",
    countryCode: "233",
    label: "EE - Estonia",
  },
  SZ: {
    locales: {
      en: "Eswatini",
      fr: "Swaziland",
      sp: "Eswatini",
      ge: "Eswatini",
      de: "Eswatini",
    },
    alpha3: "SWZ",
    countryCode: "748",
    label: "SZ - Eswatini",
  },
  ET: {
    locales: {
      en: "Ethiopia",
      fr: "Éthiopie",
      sp: "Etiopía",
      ge: "Äthiopien",
      de: "Ethiopia",
    },
    alpha3: "ETH",
    countryCode: "231",
    label: "ET - Ethiopia",
  },
  FK: {
    locales: {
      en: "Falkland Islands (Malvinas)",
      fr: "Falkland, Iles (Malvinas)",
      sp: "Islas Malvinas (Falkland Islands)",
      ge: "Falkland-Inseln (Malvinas)",
      de: "Falkland Islands (Malvinas)",
    },
    alpha3: "FLK",
    countryCode: "238",
    label: "FK - Falkland Islands (Malvinas)",
  },
  FO: {
    locales: {
      en: "Faroe Islands",
      fr: "Féroé, Iles",
      sp: "Islas Feroe",
      ge: "Färöer Inseln",
      de: "Faroe Islands",
    },
    alpha3: "FRO",
    countryCode: "234",
    label: "FO - Faroe Islands",
  },
  FJ: {
    locales: {
      en: "Fiji",
      fr: "Fidji",
      sp: "Fiji",
      ge: "Fidschi",
      de: "Fiji",
    },
    alpha3: "FJI",
    countryCode: "242",
    label: "FJ - Fiji",
  },
  FI: {
    locales: {
      en: "Finland",
      fr: "Finlande",
      sp: "Finlandia",
      ge: "Finnland",
      de: "Finland",
    },
    alpha3: "FIN",
    countryCode: "246",
    label: "FI - Finland",
  },
  FR: {
    locales: {
      en: "France",
      fr: "France",
      sp: "Francia",
      ge: "Frankreich",
      de: "France",
    },
    alpha3: "FRA",
    countryCode: "250",
    label: "FR - France",
  },
  GF: {
    locales: {
      en: "French Guiana",
      fr: "Guyane française",
      sp: "Guayana Francesa",
      ge: "Französisch-Guayana",
      de: "French Guiana",
    },
    alpha3: "GUF",
    countryCode: "254",
    label: "GF - French Guiana",
  },
  PF: {
    locales: {
      en: "French Polynesia",
      fr: "Polynésie française",
      sp: "Polinesia Francesa",
      ge: "Französisch-Polynesien",
      de: "French Polynesia",
    },
    alpha3: "PYF",
    countryCode: "258",
    label: "PF - French Polynesia",
  },
  TF: {
    locales: {
      en: "French Southern Territories",
      fr: "Terres australes françaises",
      sp: "Territorios Australes Franceses",
      ge: "Französische Südgebiete",
      de: "French Southern Territories",
    },
    alpha3: "ATF",
    countryCode: "260",
    label: "TF - French Southern Territories",
  },
  GA: {
    locales: {
      en: "Gabon",
      fr: "Gabon",
      sp: "Gabón",
      ge: "Gabun",
      de: "Gabon",
    },
    alpha3: "GAB",
    countryCode: "266",
    label: "GA - Gabon",
  },
  GM: {
    locales: {
      en: "Gambia",
      fr: "Gambie",
      sp: "Gambia",
      ge: "Gambia",
      de: "Gambia",
    },
    alpha3: "GMB",
    countryCode: "270",
    label: "GM - Gambia",
  },
  GE: {
    locales: {
      en: "Georgia",
      fr: "Géorgie",
      sp: "Georgia",
      ge: "Georgien",
      de: "Georgia",
    },
    alpha3: "GEO",
    countryCode: "268",
    label: "GE - Georgia",
  },
  DE: {
    locales: {
      en: "Germany",
      fr: "Allemagne",
      sp: "Alemania",
      ge: "Deutschland",
      de: "Germany",
    },
    alpha3: "DEU",
    countryCode: "276",
    label: "DE - Germany",
  },
  GH: {
    locales: {
      en: "Ghana",
      fr: "Ghana",
      sp: "Ghana",
      ge: "Ghana",
      de: "Ghana",
    },
    alpha3: "GHA",
    countryCode: "288",
    label: "GH - Ghana",
  },
  GI: {
    locales: {
      en: "Gibraltar",
      fr: "Gibraltar",
      sp: "Gibraltar",
      ge: "Gibraltar",
      de: "Gibraltar",
    },
    alpha3: "GIB",
    countryCode: "292",
    label: "GI - Gibraltar",
  },
  GR: {
    locales: {
      en: "Greece",
      fr: "Grèce",
      sp: "Grecia",
      ge: "Griechenland",
      de: "Greece",
    },
    alpha3: "GRC",
    countryCode: "300",
    label: "GR - Greece",
  },
  GL: {
    locales: {
      en: "Greenland",
      fr: "Groenland",
      sp: "Groenlandia",
      ge: "Grönland",
      de: "Greenland",
    },
    alpha3: "GRL",
    countryCode: "304",
    label: "GL - Greenland",
  },
  GD: {
    locales: {
      en: "Grenada",
      fr: "Grenade",
      sp: "Granada",
      ge: "Grenada",
      de: "Grenada",
    },
    alpha3: "GRD",
    countryCode: "308",
    label: "GD - Grenada",
  },
  GP: {
    locales: {
      en: "Guadeloupe",
      fr: "Guadeloupe",
      sp: "Guadalupe",
      ge: "Guadeloupe",
      de: "Guadeloupe",
    },
    alpha3: "GLP",
    countryCode: "312",
    label: "GP - Guadeloupe",
  },
  GU: {
    locales: {
      en: "Guam",
      fr: "Guam",
      sp: "Guam",
      ge: "Guam",
      de: "Guam",
    },
    alpha3: "GUM",
    countryCode: "316",
    label: "GU - Guam",
  },
  GT: {
    locales: {
      en: "Guatemala",
      fr: "Guatemala",
      sp: "Guatemala",
      ge: "Guatemala",
      de: "Guatemala",
    },
    alpha3: "GTM",
    countryCode: "320",
    label: "GT - Guatemala",
  },
  GG: {
    locales: {
      en: "Guernsey",
      fr: "Guernesey",
      sp: "Guernsey",
      ge: "Guernsey",
      de: "Guernsey",
    },
    alpha3: "GGY",
    countryCode: "831",
    label: "GG - Guernsey",
  },
  GN: {
    locales: {
      en: "Guinea",
      fr: "Guinée",
      sp: "Guinea",
      ge: "Guinea",
      de: "Guinea",
    },
    alpha3: "GIN",
    countryCode: "324",
    label: "GN - Guinea",
  },
  GW: {
    locales: {
      en: "Guinea-Bissau",
      fr: "Guinée-Bissau",
      sp: "Guinea-Bissau",
      ge: "Guinea-Bissau",
      de: "Guinea-Bissau",
    },
    alpha3: "GNB",
    countryCode: "624",
    label: "GW - Guinea-Bissau",
  },
  GY: {
    locales: {
      en: "Guyana",
      fr: "Guyana",
      sp: "Guyana",
      ge: "Guyana",
      de: "Guyana",
    },
    alpha3: "GUY",
    countryCode: "328",
    label: "GY - Guyana",
  },
  HT: {
    locales: {
      en: "Haiti",
      fr: "Haïti",
      sp: "Haití",
      ge: "Haiti",
      de: "Haiti",
    },
    alpha3: "HTI",
    countryCode: "332",
    label: "HT - Haiti",
  },
  HM: {
    locales: {
      en: "Heard Island and McDonald Islands",
      fr: "Heard et McDonald, Iles",
      sp: "Isla Heard e Islas McDonald",
      ge: "Heard Insel und McDonald Inseln",
      de: "Heard Island and McDonald Islands",
    },
    alpha3: "HMD",
    countryCode: "334",
    label: "HM - Heard Island and McDonald Islands",
  },
  VA: {
    locales: {
      en: "Holy See",
      fr: "Vatican, État de la Cité du",
      sp: "Santa Sede (Estado de la Ciudad del Vaticano)",
      ge: "(Heiliger Stuhl) Vatikanstaat",
      de: "Vatican City State",
    },
    alpha3: "VAT",
    countryCode: "336",
    label: "VA - Holy See",
  },
  HN: {
    locales: {
      en: "Honduras",
      fr: "Honduras",
      sp: "Honduras",
      ge: "Honduras",
      de: "Honduras",
    },
    alpha3: "HND",
    countryCode: "340",
    label: "HN - Honduras",
  },
  HK: {
    locales: {
      en: "Hong Kong",
      fr: "Hong-Kong",
      sp: "Hong Kong",
      ge: "Hongkong",
      de: "Hong Kong",
    },
    alpha3: "HKG",
    countryCode: "344",
    label: "HK - Hong Kong",
  },
  HU: {
    locales: {
      en: "Hungary",
      fr: "Hongrie",
      sp: "Hungría",
      ge: "Ungarn",
      de: "Hungary",
    },
    alpha3: "HUN",
    countryCode: "348",
    label: "HU - Hungary",
  },
  IS: {
    locales: {
      en: "Iceland",
      fr: "Islande",
      sp: "Islandia",
      ge: "Island",
      de: "Iceland",
    },
    alpha3: "ISL",
    countryCode: "352",
    label: "IS - Iceland",
  },
  IN: {
    locales: {
      en: "India",
      fr: "Inde",
      sp: "India",
      ge: "Indien",
      de: "India",
    },
    alpha3: "IND",
    countryCode: "356",
    label: "IN - India",
  },
  ID: {
    locales: {
      en: "Indonesia",
      fr: "Indonésie",
      sp: "Indonesia",
      ge: "Indonesien",
      de: "Indonesia",
    },
    alpha3: "IDN",
    countryCode: "360",
    label: "ID - Indonesia",
  },
  IR: {
    locales: {
      en: "Iran (Islamic Republic of)",
      fr: "Iran",
      sp: "Irán",
      ge: "Iran",
      de: "Iran",
    },
    alpha3: "IRN",
    countryCode: "364",
    label: "IR - Iran (Islamic Republic of)",
  },
  IQ: {
    locales: {
      en: "Iraq",
      fr: "Irak",
      sp: "Irak",
      ge: "Irak",
      de: "Iraq",
    },
    alpha3: "IRQ",
    countryCode: "368",
    label: "IQ - Iraq",
  },
  IE: {
    locales: {
      en: "Ireland",
      fr: "Irlande",
      sp: "Irlanda",
      ge: "Irland",
      de: "Ireland",
    },
    alpha3: "IRL",
    countryCode: "372",
    label: "IE - Ireland",
  },
  IM: {
    locales: {
      en: "Isle of Man",
      fr: "Ile de Man",
      sp: "Isla de Man",
      ge: "Insel Man",
      de: "Isle of Man",
    },
    alpha3: "IMN",
    countryCode: "833",
    label: "IM - Isle of Man",
  },
  IL: {
    locales: {
      en: "Israel",
      fr: "Israël",
      sp: "Israel",
      ge: "Israel",
      de: "Israel",
    },
    alpha3: "ISR",
    countryCode: "376",
    label: "IL - Israel",
  },
  IT: {
    locales: {
      en: "Italy",
      fr: "Italie",
      sp: "Italia",
      ge: "Italien",
      de: "Italy",
    },
    alpha3: "ITA",
    countryCode: "380",
    label: "IT - Italy",
  },
  JM: {
    locales: {
      en: "Jamaica",
      fr: "Jamaïque",
      sp: "Jamaica",
      ge: "Jamaika",
      de: "Jamaica",
    },
    alpha3: "JAM",
    countryCode: "388",
    label: "JM - Jamaica",
  },
  JP: {
    locales: {
      en: "Japan",
      fr: "Japon",
      sp: "Japón",
      ge: "Japan",
      de: "Japan",
    },
    alpha3: "JPN",
    countryCode: "392",
    label: "JP - Japan",
  },
  JE: {
    locales: {
      en: "Jersey",
      fr: "Jersey",
      sp: "Jersey",
      ge: "Jersey",
      de: "Jersey",
    },
    alpha3: "JEY",
    countryCode: "832",
    label: "JE - Jersey",
  },
  JO: {
    locales: {
      en: "Jordan",
      fr: "Jordanie",
      sp: "Jordania",
      ge: "Jordanien",
      de: "Jordan",
    },
    alpha3: "JOR",
    countryCode: "400",
    label: "JO - Jordan",
  },
  KZ: {
    locales: {
      en: "Kazakhstan",
      fr: "Kazakhstan",
      sp: "Kazajistán",
      ge: "Kasachstan",
      de: "Kazakhstan",
    },
    alpha3: "KAZ",
    countryCode: "398",
    label: "KZ - Kazakhstan",
  },
  KE: {
    locales: {
      en: "Kenya",
      fr: "Kenya",
      sp: "Kenia",
      ge: "Kenia",
      de: "Kenya",
    },
    alpha3: "KEN",
    countryCode: "404",
    label: "KE - Kenya",
  },
  KI: {
    locales: {
      en: "Kiribati",
      fr: "Kiribati",
      sp: "Kiribati",
      ge: "Kiribati",
      de: "Kiribati",
    },
    alpha3: "KIR",
    countryCode: "296",
    label: "KI - Kiribati",
  },
  KP: {
    locales: {
      en: "Korea (Democratic People's Republic of)",
      fr: "Corée du Nord",
      sp: "Corea (del Norte)",
      ge: "Korea (Norden)",
      de: "Korea (North)",
    },
    alpha3: "PRK",
    countryCode: "408",
    label: "KP - Korea (Democratic People's Republic of)",
  },
  KR: {
    locales: {
      en: "Korea, Republic of",
      fr: "Corée, République de",
      sp: "Corea, República de",
      ge: "Korea, Republik",
      de: "Korea, Republic of",
    },
    alpha3: "KOR",
    countryCode: "410",
    label: "KR - Korea, Republic of",
  },
  KW: {
    locales: {
      en: "Kuwait",
      fr: "Koweït",
      sp: "Kuwait",
      ge: "Kuwait",
      de: "Kuwait",
    },
    alpha3: "KWT",
    countryCode: "414",
    label: "KW - Kuwait",
  },
  KG: {
    locales: {
      en: "Kyrgyzstan",
      fr: "Kirghizistan",
      sp: "Kirguistán",
      ge: "Kirgisistan",
      de: "Kyrgyzstan",
    },
    alpha3: "KGZ",
    countryCode: "417",
    label: "KG - Kyrgyzstan",
  },
  LA: {
    locales: {
      en: "Lao People's Democratic Republic",
      fr: "Lao, République démocratique populaire",
      sp: "República Democrática Popular de Laos",
      ge: "Lao, Demokratische Volksrepublik",
      de: "Lao People's Democratic Republic",
    },
    alpha3: "LAO",
    countryCode: "418",
    label: "LA - Lao People's Democratic Republic",
  },
  LV: {
    locales: {
      en: "Latvia",
      fr: "Lettonie",
      sp: "Letonia",
      ge: "Lettland",
      de: "Latvia",
    },
    alpha3: "LVA",
    countryCode: "428",
    label: "LV - Latvia",
  },
  LB: {
    locales: {
      en: "Lebanon",
      fr: "Liban",
      sp: "Líbano",
      ge: "Libanon",
      de: "Lebanon",
    },
    alpha3: "LBN",
    countryCode: "422",
    label: "LB - Lebanon",
  },
  LS: {
    locales: {
      en: "Lesotho",
      fr: "Lesotho",
      sp: "Lesotho",
      ge: "Lesotho",
      de: "Lesotho",
    },
    alpha3: "LSO",
    countryCode: "426",
    label: "LS - Lesotho",
  },
  LR: {
    locales: {
      en: "Liberia",
      fr: "Libéria",
      sp: "Liberia",
      ge: "Liberia",
      de: "Liberia",
    },
    alpha3: "LBR",
    countryCode: "430",
    label: "LR - Liberia",
  },
  LY: {
    locales: {
      en: "Libya",
      fr: "Libye",
      sp: "Libia",
      ge: "Libyen",
      de: "Libya",
    },
    alpha3: "LBY",
    countryCode: "434",
    label: "LY - Libya",
  },
  LI: {
    locales: {
      en: "Liechtenstein",
      fr: "Liechtenstein",
      sp: "Liechtenstein",
      ge: "Liechtenstein",
      de: "Liechtenstein",
    },
    alpha3: "LIE",
    countryCode: "438",
    label: "LI - Liechtenstein",
  },
  LT: {
    locales: {
      en: "Lithuania",
      fr: "Lituanie",
      sp: "Lituania",
      ge: "Litauen",
      de: "Lithuania",
    },
    alpha3: "LTU",
    countryCode: "440",
    label: "LT - Lithuania",
  },
  LU: {
    locales: {
      en: "Luxembourg",
      fr: "Luxembourg",
      sp: "Luxemburgo",
      ge: "Luxemburg",
      de: "Luxembourg",
    },
    alpha3: "LUX",
    countryCode: "442",
    label: "LU - Luxembourg",
  },
  MO: {
    locales: {
      en: "Macao",
      fr: "Macao",
      sp: "Macao",
      ge: "Macau",
      de: "Macau",
    },
    alpha3: "MAC",
    countryCode: "446",
    label: "MO - Macao",
  },
  MG: {
    locales: {
      en: "Madagascar",
      fr: "Madagascar",
      sp: "Madagascar",
      ge: "Madagaskar",
      de: "Madagascar",
    },
    alpha3: "MDG",
    countryCode: "450",
    label: "MG - Madagascar",
  },
  MW: {
    locales: {
      en: "Malawi",
      fr: "Malawi",
      sp: "Malawi",
      ge: "Malawi",
      de: "Malawi",
    },
    alpha3: "MWI",
    countryCode: "454",
    label: "MW - Malawi",
  },
  MY: {
    locales: {
      en: "Malaysia",
      fr: "Malaisie",
      sp: "Malasia",
      ge: "Malaysia",
      de: "Malaysia",
    },
    alpha3: "MYS",
    countryCode: "458",
    label: "MY - Malaysia",
  },
  MV: {
    locales: {
      en: "Maldives",
      fr: "Maldives",
      sp: "Maldivas",
      ge: "Malediven",
      de: "Maldives",
    },
    alpha3: "MDV",
    countryCode: "462",
    label: "MV - Maldives",
  },
  ML: {
    locales: {
      en: "Mali",
      fr: "Mali",
      sp: "Malí",
      ge: "Mali",
      de: "Mali",
    },
    alpha3: "MLI",
    countryCode: "466",
    label: "ML - Mali",
  },
  MT: {
    locales: {
      en: "Malta",
      fr: "Malte",
      sp: "Malta",
      ge: "Malta",
      de: "Malta",
    },
    alpha3: "MLT",
    countryCode: "470",
    label: "MT - Malta",
  },
  MH: {
    locales: {
      en: "Marshall Islands",
      fr: "Iles Marshall",
      sp: "Islas Marshall",
      ge: "Marshallinseln",
      de: "Marshall Islands",
    },
    alpha3: "MHL",
    countryCode: "584",
    label: "MH - Marshall Islands",
  },
  MQ: {
    locales: {
      en: "Martinique",
      fr: "Martinique",
      sp: "Martinica",
      ge: "Martinique",
      de: "Martinique",
    },
    alpha3: "MTQ",
    countryCode: "474",
    label: "MQ - Martinique",
  },
  MR: {
    locales: {
      en: "Mauritania",
      fr: "Mauritanie",
      sp: "Mauritania",
      ge: "Mauretanien",
      de: "Mauritania",
    },
    alpha3: "MRT",
    countryCode: "478",
    label: "MR - Mauritania",
  },
  MU: {
    locales: {
      en: "Mauritius",
      fr: "Maurice",
      sp: "Mauricio",
      ge: "Mauritius",
      de: "Mauritius",
    },
    alpha3: "MUS",
    countryCode: "480",
    label: "MU - Mauritius",
  },
  YT: {
    locales: {
      en: "Mayotte",
      fr: "Mayotte",
      sp: "Mayotte",
      ge: "Mayotte",
      de: "Mayotte",
    },
    alpha3: "MYT",
    countryCode: "175",
    label: "YT - Mayotte",
  },
  MX: {
    locales: {
      en: "Mexico",
      fr: "Mexique",
      sp: "México",
      ge: "Mexiko",
      de: "Mexico",
    },
    alpha3: "MEX",
    countryCode: "484",
    label: "MX - Mexico",
  },
  FM: {
    locales: {
      en: "Micronesia (Federated States of)",
      fr: "Micronésie, États fédérés de",
      sp: "Micronesia, Estados Federados de",
      ge: "Mikronesien, Föderierte Staaten von",
      de: "Micronesia, Federated States of",
    },
    alpha3: "FSM",
    countryCode: "583",
    label: "FM - Micronesia (Federated States of)",
  },
  MD: {
    locales: {
      en: "Moldova, Republic of",
      fr: "Moldavie, République de ",
      sp: "Moldavia, República de",
      ge: "Moldau, Republik",
      de: "Moldova, Republic of",
    },
    alpha3: "MDA",
    countryCode: "498",
    label: "MD - Moldova, Republic of",
  },
  MC: {
    locales: {
      en: "Monaco",
      fr: "Monaco",
      sp: "Mónaco",
      ge: "Monaco",
      de: "Monaco",
    },
    alpha3: "MCO",
    countryCode: "492",
    label: "MC - Monaco",
  },
  MN: {
    locales: {
      en: "Mongolia",
      fr: "Mongalie",
      sp: "Mongolia",
      ge: "Mongolei",
      de: "Mongolia",
    },
    alpha3: "MNG",
    countryCode: "496",
    label: "MN - Mongolia",
  },
  ME: {
    locales: {
      en: "Montenegro",
      fr: "Monténégro",
      sp: "Montenegro",
      ge: "Montenegro",
      de: "Montenegro",
    },
    alpha3: "MNE",
    countryCode: "499",
    label: "ME - Montenegro",
  },
  MS: {
    locales: {
      en: "Montserrat",
      fr: "Montserrat",
      sp: "Montserrat",
      ge: "Montserrat",
      de: "Montserrat",
    },
    alpha3: "MSR",
    countryCode: "500",
    label: "MS - Montserrat",
  },
  MA: {
    locales: {
      en: "Morocco",
      fr: "Maroc",
      sp: "Marruecos",
      ge: "Marokko",
      de: "Morocco",
    },
    alpha3: "MAR",
    countryCode: "504",
    label: "MA - Morocco",
  },
  MZ: {
    locales: {
      en: "Mozambique",
      fr: "Mozambique",
      sp: "Mozambique",
      ge: "Mosambik",
      de: "Mozambique",
    },
    alpha3: "MOZ",
    countryCode: "508",
    label: "MZ - Mozambique",
  },
  MM: {
    locales: {
      en: "Myanmar",
      fr: "Myanmar",
      sp: "Myanmar",
      ge: "Myanmar",
      de: "Myanmar",
    },
    alpha3: "MMR",
    countryCode: "104",
    label: "MM - Myanmar",
  },
  NA: {
    locales: {
      en: "Namibia",
      fr: "Namibie",
      sp: "Namibia",
      ge: "Namibia",
      de: "Namibia",
    },
    alpha3: "NAM",
    countryCode: "516",
    label: "NA - Namibia",
  },
  NR: {
    locales: {
      en: "Nauru",
      fr: "Nauru",
      sp: "Nauru",
      ge: "Nauru",
      de: "Nauru",
    },
    alpha3: "NRU",
    countryCode: "520",
    label: "NR - Nauru",
  },
  NP: {
    locales: {
      en: "Nepal",
      fr: "Népal",
      sp: "Nepal",
      ge: "Nepal",
      de: "Nepal",
    },
    alpha3: "NPL",
    countryCode: "524",
    label: "NP - Nepal",
  },
  NL: {
    locales: {
      en: "Netherlands",
      fr: "Pays-Bas",
      sp: "Países Bajos",
      ge: "Niederlande",
      de: "Netherlands",
    },
    alpha3: "NLD",
    countryCode: "528",
    label: "NL - Netherlands",
  },
  NC: {
    locales: {
      en: "New Caledonia",
      fr: "Nouvelle-Calédonie",
      sp: "Nueva Caledonia",
      ge: "Neukaledonien",
      de: "New Caledonia",
    },
    alpha3: "NCL",
    countryCode: "540",
    label: "NC - New Caledonia",
  },
  NZ: {
    locales: {
      en: "New Zealand",
      fr: "Nouvelle-Zélande",
      sp: "Nueva Zelanda",
      ge: "Neuseeland",
      de: "New Zealand",
    },
    alpha3: "NZL",
    countryCode: "554",
    label: "NZ - New Zealand",
  },
  NI: {
    locales: {
      en: "Nicaragua",
      fr: "Nicaragua",
      sp: "Nicaragua",
      ge: "Nicaragua",
      de: "Nicaragua",
    },
    alpha3: "NIC",
    countryCode: "558",
    label: "NI - Nicaragua",
  },
  NE: {
    locales: {
      en: "Niger",
      fr: "Niger",
      sp: "Níger",
      ge: "Niger",
      de: "Niger",
    },
    alpha3: "NER",
    countryCode: "562",
    label: "NE - Niger",
  },
  NG: {
    locales: {
      en: "Nigeria",
      fr: "Nigéria",
      sp: "Nigeria",
      ge: "Nigeria",
      de: "Nigeria",
    },
    alpha3: "NGA",
    countryCode: "566",
    label: "NG - Nigeria",
  },
  NU: {
    locales: {
      en: "Niue",
      fr: "Niue",
      sp: "Niue",
      ge: "Niue",
      de: "Niue",
    },
    alpha3: "NIU",
    countryCode: "570",
    label: "NU - Niue",
  },
  NF: {
    locales: {
      en: "Norfolk Island",
      fr: "Norfolk, Ile",
      sp: "Isla de Norfolk",
      ge: "Norfolk Insel",
      de: "Norfolk Island",
    },
    alpha3: "NFK",
    countryCode: "574",
    label: "NF - Norfolk Island",
  },
  MK: {
    locales: {
      en: "North Macedonia",
      fr: "Macédoine du Nord",
      sp: "Macedonia del Norte",
      ge: "Nordmazedonien",
      de: "North Macedonia",
    },
    alpha3: "MKD",
    countryCode: "807",
    label: "MK - North Macedonia",
  },
  MP: {
    locales: {
      en: "Northern Mariana Islands",
      fr: "Mariannes du Nord, Iles",
      sp: "Islas Marianas del Norte",
      ge: "Nördliche Marianen Inseln",
      de: "Northern Mariana Islands",
    },
    alpha3: "MNP",
    countryCode: "580",
    label: "MP - Northern Mariana Islands",
  },
  NO: {
    locales: {
      en: "Norway",
      fr: "Norvège",
      sp: "Noruega",
      ge: "Norwegen",
      de: "Norway",
    },
    alpha3: "NOR",
    countryCode: "578",
    label: "NO - Norway",
  },
  OM: {
    locales: {
      en: "Oman",
      fr: "Oman",
      sp: "Omán",
      ge: "Oman",
      de: "Oman",
    },
    alpha3: "OMN",
    countryCode: "512",
    label: "OM - Oman",
  },
  PK: {
    locales: {
      en: "Pakistan",
      fr: "Pakistan",
      sp: "Pakistán",
      ge: "Pakistan",
      de: "Pakistan",
    },
    alpha3: "PAK",
    countryCode: "586",
    label: "PK - Pakistan",
  },
  PW: {
    locales: {
      en: "Palau",
      fr: "Palaos",
      sp: "Palau",
      ge: "Palaos",
      de: "Palau",
    },
    alpha3: "PLW",
    countryCode: "585",
    label: "PW - Palau",
  },
  PS: {
    locales: {
      en: "Palestine, State of",
      fr: "Palestine, État de",
      sp: "Palestina, Estado de",
      ge: "Palästina, Staat von",
      de: "Palestine, State of",
    },
    alpha3: "PSE",
    countryCode: "275",
    label: "PS - Palestine, State of",
  },
  PA: {
    locales: {
      en: "Panama",
      fr: "Panama",
      sp: "Panamá",
      ge: "Panama",
      de: "Panama",
    },
    alpha3: "PAN",
    countryCode: "591",
    label: "PA - Panama",
  },
  PG: {
    locales: {
      en: "Papua New Guinea",
      fr: "Papouasie-Nouvelle-Guinée",
      sp: "Papúa Nueva Guinea",
      ge: "Papua-Neuguinea",
      de: "Papua New Guinea",
    },
    alpha3: "PNG",
    countryCode: "598",
    label: "PG - Papua New Guinea",
  },
  PY: {
    locales: {
      en: "Paraguay",
      fr: "Paraguay",
      sp: "Paraguay",
      ge: "Paraguay",
      de: "Paraguay",
    },
    alpha3: "PRY",
    countryCode: "600",
    label: "PY - Paraguay",
  },
  PE: {
    locales: {
      en: "Peru",
      fr: "Pérou",
      sp: "Perú",
      ge: "Peru",
      de: "Peru",
    },
    alpha3: "PER",
    countryCode: "604",
    label: "PE - Peru",
  },
  PH: {
    locales: {
      en: "Philippines",
      fr: "Philippines",
      sp: "Filipinas",
      ge: "Philippinen",
      de: "Philippines",
    },
    alpha3: "PHL",
    countryCode: "608",
    label: "PH - Philippines",
  },
  PN: {
    locales: {
      en: "Pitcairn",
      fr: "Pitcairn",
      sp: "Pitcairn",
      ge: "Pitcairn",
      de: "Pitcairn",
    },
    alpha3: "PCN",
    countryCode: "612",
    label: "PN - Pitcairn",
  },
  PL: {
    locales: {
      en: "Poland",
      fr: "Pologne",
      sp: "Polonia",
      ge: "Polen",
      de: "Poland",
    },
    alpha3: "POL",
    countryCode: "616",
    label: "PL - Poland",
  },
  PT: {
    locales: {
      en: "Portugal",
      fr: "Portugal",
      sp: "Portugal",
      ge: "Portugal",
      de: "Portugal",
    },
    alpha3: "PRT",
    countryCode: "620",
    label: "PT - Portugal",
  },
  PR: {
    locales: {
      en: "Puerto Rico",
      fr: "Porto Rico",
      sp: "Puerto Rico",
      ge: "Puerto Rico",
      de: "Puerto Rico",
    },
    alpha3: "PRI",
    countryCode: "630",
    label: "PR - Puerto Rico",
  },
  QA: {
    locales: {
      en: "Qatar",
      fr: "Quatar",
      sp: "Qatar",
      ge: "Katar",
      de: "Qatar",
    },
    alpha3: "QAT",
    countryCode: "634",
    label: "QA - Qatar",
  },
  RE: {
    locales: {
      en: "Réunion",
      fr: "Réunion",
      sp: "Isla de la Reunión",
      ge: "Réunion, La",
      de: "Reunion Island",
    },
    alpha3: "REU",
    countryCode: "638",
    label: "RE - Réunion",
  },
  RO: {
    locales: {
      en: "Romania",
      fr: "Roumanie",
      sp: "Rumanía",
      ge: "Rumänien",
      de: "Romania",
    },
    alpha3: "ROU",
    countryCode: "642",
    label: "RO - Romania",
  },
  RU: {
    locales: {
      en: "Russian Federation",
      fr: "Russie, Fédération de",
      sp: "Rusia, Federación de",
      ge: "Russische Föderation",
      de: "Russia, Federation of",
    },
    alpha3: "RUS",
    countryCode: "643",
    label: "RU - Russian Federation",
  },
  RW: {
    locales: {
      en: "Rwanda",
      fr: "Rwanda",
      sp: "Ruanda",
      ge: "Ruanda",
      de: "Rwanda",
    },
    alpha3: "RWA",
    countryCode: "646",
    label: "RW - Rwanda",
  },
  BL: {
    locales: {
      en: "Saint Barthélemy",
      fr: "Saint-Barthélemy",
      sp: "San Bartolomé",
      ge: "Saint-Barthélemy",
      de: "Saint Barthélemy",
    },
    alpha3: "BLM",
    countryCode: "652",
    label: "BL - Saint Barthélemy",
  },
  SH: {
    locales: {
      en: "Saint Helena, Ascension and Tristan da Cunha",
      fr: "Sainte-Hélène, Ascension et Tristan da Cunha",
      sp: "Santa Elena, Ascensión y Tristán da Cunha",
      ge: "St. Helena, Ascension und Tristan da Cunha",
      de: "St Helena, Ascension and Tristan da Cunha",
    },
    alpha3: "SHN",
    countryCode: "654",
    label: "SH - Saint Helena, Ascension and Tristan da Cunha",
  },
  KN: {
    locales: {
      en: "Saint Kitts and Nevis",
      fr: "Saint-Kitts-et-Nevis",
      sp: "San Cristóbal y Nieves",
      ge: "St. Kitts und Nevis",
      de: "Saint Kitts and Nevis",
    },
    alpha3: "KNA",
    countryCode: "659",
    label: "KN - Saint Kitts and Nevis",
  },
  LC: {
    locales: {
      en: "Saint Lucia",
      fr: "Sainte-Lucie",
      sp: "Santa Lucía",
      ge: "St. Lucia",
      de: "Saint Lucia",
    },
    alpha3: "LCA",
    countryCode: "662",
    label: "LC - Saint Lucia",
  },
  MF: {
    locales: {
      en: "Saint Martin (French part)",
      fr: "Saint-Martin (partie française)",
      sp: "Saint-Martin (parte francesa)",
      ge: "Saint-Martin (französischer Teil)",
      de: "Saint Martin (French part)",
    },
    alpha3: "MAF",
    countryCode: "663",
    label: "MF - Saint Martin (French part)",
  },
  PM: {
    locales: {
      en: "Saint Pierre and Miquelon",
      fr: "Saint-Pierre-et-Miquelon",
      sp: "San Pedro y Miquelón",
      ge: "Saint-Pierre und Miquelon",
      de: "Saint Pierre and Miquelon",
    },
    alpha3: "SPM",
    countryCode: "666",
    label: "PM - Saint Pierre and Miquelon",
  },
  VC: {
    locales: {
      en: "Saint Vincent and the Grenadines",
      fr: "Saint-Vincent-et-les Grenadines",
      sp: "San Vicente y las Granadinas",
      ge: "St. Vincent und die Grenadinen",
      de: "Saint Vincent and the Grenadines",
    },
    alpha3: "VCT",
    countryCode: "670",
    label: "VC - Saint Vincent and the Grenadines",
  },
  WS: {
    locales: {
      en: "Samoa",
      fr: "Samoa",
      sp: "Samoa",
      ge: "Samoa",
      de: "Samoa",
    },
    alpha3: "WSM",
    countryCode: "882",
    label: "WS - Samoa",
  },
  SM: {
    locales: {
      en: "San Marino",
      fr: "Saint-Marin",
      sp: "San Marino",
      ge: "San Marin",
      de: "San Marino",
    },
    alpha3: "SMR",
    countryCode: "674",
    label: "SM - San Marino",
  },
  ST: {
    locales: {
      en: "Sao Tome and Principe",
      fr: "Sao Tomé-et-Principe",
      sp: "Santo Tomé y Príncipe",
      ge: "Sao Tomé und Principe",
      de: "Sao Tome and Principe",
    },
    alpha3: "STP",
    countryCode: "678",
    label: "ST - Sao Tome and Principe",
  },
  SA: {
    locales: {
      en: "Saudi Arabia",
      fr: "Arabie saoudite",
      sp: "Arabia Saudí",
      ge: "Saudi-Arabien",
      de: "Saudi Arabia",
    },
    alpha3: "SAU",
    countryCode: "682",
    label: "SA - Saudi Arabia",
  },
  SN: {
    locales: {
      en: "Senegal",
      fr: "Sénégal",
      sp: "Senegal",
      ge: "Senegal",
      de: "Senegal",
    },
    alpha3: "SEN",
    countryCode: "686",
    label: "SN - Senegal",
  },
  RS: {
    locales: {
      en: "Serbia",
      fr: "Serbie",
      sp: "Serbia",
      ge: "Serbien",
      de: "Serbia",
    },
    alpha3: "SRB",
    countryCode: "688",
    label: "RS - Serbia",
  },
  SC: {
    locales: {
      en: "Seychelles",
      fr: "Seychelles",
      sp: "Seychelles",
      ge: "Seychellen",
      de: "Seychelles",
    },
    alpha3: "SYC",
    countryCode: "690",
    label: "SC - Seychelles",
  },
  SL: {
    locales: {
      en: "Sierra Leone",
      fr: "Sierra Leone",
      sp: "Sierra Leona",
      ge: "Sierra Leone",
      de: "Sierra Leone",
    },
    alpha3: "SLE",
    countryCode: "694",
    label: "SL - Sierra Leone",
  },
  SG: {
    locales: {
      en: "Singapore",
      fr: "Singapour",
      sp: "Singapur",
      ge: "Singapur",
      de: "Singapore",
    },
    alpha3: "SGP",
    countryCode: "702",
    label: "SG - Singapore",
  },
  SX: {
    locales: {
      en: "Sint Maarten (Dutch part)",
      fr: "Saint-Martin (partie néerlandaise)",
      sp: "San Martín (parte holandesa)",
      ge: "Saint-Martin (niederländischer Teil)",
      de: "Sint Maarten (Dutch part)",
    },
    alpha3: "SXM",
    countryCode: "534",
    label: "SX - Sint Maarten (Dutch part)",
  },
  SK: {
    locales: {
      en: "Slovakia",
      fr: "Slovaquie",
      sp: "Eslovaquia",
      ge: "Slowakei",
      de: "Slovakia",
    },
    alpha3: "SVK",
    countryCode: "703",
    label: "SK - Slovakia",
  },
  SI: {
    locales: {
      en: "Slovenia",
      fr: "Slovénie",
      sp: "Eslovenia",
      ge: "Slowenien",
      de: "Slovenia",
    },
    alpha3: "SVN",
    countryCode: "705",
    label: "SI - Slovenia",
  },
  SB: {
    locales: {
      en: "Solomon Islands",
      fr: "Salomon, Iles",
      sp: "Islas Salomón",
      ge: "Salomon-Inseln",
      de: "Solomon Islands",
    },
    alpha3: "SLB",
    countryCode: "90",
    label: "SB - Solomon Islands",
  },
  SO: {
    locales: {
      en: "Somalia",
      fr: "Somalie",
      sp: "Somalia",
      ge: "Somalia",
      de: "Somalia",
    },
    alpha3: "SOM",
    countryCode: "706",
    label: "SO - Somalia",
  },
  ZA: {
    locales: {
      en: "South Africa",
      fr: "Afrique du Sud",
      sp: "Sudáfrica",
      ge: "Südafrika",
      de: "South Africa",
    },
    alpha3: "ZAF",
    countryCode: "710",
    label: "ZA - South Africa",
  },
  GS: {
    locales: {
      en: "South Georgia and the South Sandwich Islands",
      fr: "Géorgie du Sud, Iles Sandwich du Sud",
      sp: "Georgia del Sur y las Islas Sandwich del Sur",
      ge: "Südgeorgien und die Südlichen Sandwichinseln",
      de: "South Georgia and the South Sandwich Islands",
    },
    alpha3: "SGS",
    countryCode: "239",
    label: "GS - South Georgia and the South Sandwich Islands",
  },
  SS: {
    locales: {
      en: "South Sudan",
      fr: "Soudan du Sud",
      sp: "Sudán del Sur",
      ge: "Südsudan",
      de: "South Sudan",
    },
    alpha3: "SSD",
    countryCode: "728",
    label: "SS - South Sudan",
  },
  ES: {
    locales: {
      en: "Spain",
      fr: "Espagne",
      sp: "España",
      ge: "Spanien",
      de: "Spain",
    },
    alpha3: "ESP",
    countryCode: "724",
    label: "ES - Spain",
  },
  LK: {
    locales: {
      en: "Sri Lanka",
      fr: "Sri Lanka",
      sp: "Sri Lanka",
      ge: "Sri Lanka",
      de: "Sri Lanka",
    },
    alpha3: "LKA",
    countryCode: "144",
    label: "LK - Sri Lanka",
  },
  SD: {
    locales: {
      en: "Sudan",
      fr: "Soudan",
      sp: "Sudán",
      ge: "Sudan",
      de: "Sudan",
    },
    alpha3: "SDN",
    countryCode: "729",
    label: "SD - Sudan",
  },
  SR: {
    locales: {
      en: "Suriname",
      fr: "Surinam",
      sp: "Surinam",
      ge: "Surinam",
      de: "Suriname",
    },
    alpha3: "SUR",
    countryCode: "740",
    label: "SR - Suriname",
  },
  SJ: {
    locales: {
      en: "Svalbard and Jan Mayen",
      fr: "Svalbard et Ile Jan Mayen",
      sp: "Islas Svalbard y Jan Mayen",
      ge: "Svalbard und Jan Mayen",
      de: "Svalbard and Jan Mayen Island",
    },
    alpha3: "SJM",
    countryCode: "744",
    label: "SJ - Svalbard and Jan Mayen",
  },
  SE: {
    locales: {
      en: "Sweden",
      fr: "Suède",
      sp: "Suecia",
      ge: "Schweden",
      de: "Sweden",
    },
    alpha3: "SWE",
    countryCode: "752",
    label: "SE - Sweden",
  },
  CH: {
    locales: {
      en: "Switzerland",
      fr: "Suisse",
      sp: "Suiza",
      ge: "Schweiz",
      de: "Switzerland",
    },
    alpha3: "CHE",
    countryCode: "756",
    label: "CH - Switzerland",
  },
  SY: {
    locales: {
      en: "Syrian Arab Republic",
      fr: "Syrie",
      sp: "Siria",
      ge: "Syrien",
      de: "Syria",
    },
    alpha3: "SYR",
    countryCode: "760",
    label: "SY - Syrian Arab Republic",
  },
  TW: {
    locales: {
      en: "Taiwan, Province of China",
      fr: "Taïwan, Province de Chine",
      sp: "Taiwán, provincia de China",
      ge: "Taiwan, Provinz China",
      de: "Taiwan, Province of China",
    },
    alpha3: "TWN",
    countryCode: "158",
    label: "TW - Taiwan, Province of China",
  },
  TJ: {
    locales: {
      en: "Tajikistan",
      fr: "Tadjikistan",
      sp: "Tayikistán",
      ge: "Tadschikistan",
      de: "Tajikistan",
    },
    alpha3: "TJK",
    countryCode: "762",
    label: "TJ - Tajikistan",
  },
  TZ: {
    locales: {
      en: "Tanzania, United Republic of",
      fr: "Tanzanie",
      sp: "Tanzania",
      ge: "Tansania",
      de: "Tanzania",
    },
    alpha3: "TZA",
    countryCode: "834",
    label: "TZ - Tanzania, United Republic of",
  },
  TH: {
    locales: {
      en: "Thailand",
      fr: "Thaïlande",
      sp: "Tailandia",
      ge: "Thailand",
      de: "Thailand",
    },
    alpha3: "THA",
    countryCode: "764",
    label: "TH - Thailand",
  },
  TL: {
    locales: {
      en: "Timor-Leste",
      fr: "Timor-Leste",
      sp: "Timor-Leste",
      ge: "Timor-Leste",
      de: "Timor-Leste",
    },
    alpha3: "TLS",
    countryCode: "626",
    label: "TL - Timor-Leste",
  },
  TG: {
    locales: {
      en: "Togo",
      fr: "Togo",
      sp: "Togo",
      ge: "Togo",
      de: "Togo",
    },
    alpha3: "TGO",
    countryCode: "768",
    label: "TG - Togo",
  },
  TK: {
    locales: {
      en: "Tokelau",
      fr: "Tokelau",
      sp: "Tokelau",
      ge: "Tokelau",
      de: "Tokelau",
    },
    alpha3: "TKL",
    countryCode: "772",
    label: "TK - Tokelau",
  },
  TO: {
    locales: {
      en: "Tonga",
      fr: "Tonga",
      sp: "Tonga",
      ge: "Tonga",
      de: "Tonga",
    },
    alpha3: "TON",
    countryCode: "776",
    label: "TO - Tonga",
  },
  TT: {
    locales: {
      en: "Trinidad and Tobago",
      fr: "Trinité-et-Tobago",
      sp: "Trinidad y Tobago",
      ge: "Trinidad und Tobago",
      de: "Trinidad and Tobago",
    },
    alpha3: "TTO",
    countryCode: "780",
    label: "TT - Trinidad and Tobago",
  },
  TN: {
    locales: {
      en: "Tunisia",
      fr: "Tunisie",
      sp: "Túnez",
      ge: "Tunesien",
      de: "Tunisia",
    },
    alpha3: "TUN",
    countryCode: "788",
    label: "TN - Tunisia",
  },
  TR: {
    locales: {
      en: "Turkey",
      fr: "Turquie",
      sp: "Turquía",
      ge: "Türkei",
      de: "Turkey",
    },
    alpha3: "TUR",
    countryCode: "792",
    label: "TR - Turkey",
  },
  TM: {
    locales: {
      en: "Turkmenistan",
      fr: "Turkménistan",
      sp: "Turkmenistán",
      ge: "Turkmenistan",
      de: "Turkmenistan",
    },
    alpha3: "TKM",
    countryCode: "795",
    label: "TM - Turkmenistan",
  },
  TC: {
    locales: {
      en: "Turks and Caicos Islands",
      fr: "Turques-et-Caïques, Iles",
      sp: "Islas Turcas y Caicos",
      ge: "Turks- und Caicosinseln",
      de: "Turks and Caicos Islands",
    },
    alpha3: "TCA",
    countryCode: "796",
    label: "TC - Turks and Caicos Islands",
  },
  TV: {
    locales: {
      en: "Tuvalu",
      fr: "Tuvalu",
      sp: "Tuvalu",
      ge: "Tuvalu",
      de: "Tuvalu",
    },
    alpha3: "TUV",
    countryCode: "798",
    label: "TV - Tuvalu",
  },
  UG: {
    locales: {
      en: "Uganda",
      fr: "Ouganda",
      sp: "Uganda",
      ge: "Uganda",
      de: "Uganda",
    },
    alpha3: "UGA",
    countryCode: "800",
    label: "UG - Uganda",
  },
  UA: {
    locales: {
      en: "Ukraine",
      fr: "Ukraine",
      sp: "Ucrania",
      ge: "Ukraine",
      de: "Ukraine",
    },
    alpha3: "UKR",
    countryCode: "804",
    label: "UA - Ukraine",
  },
  AE: {
    locales: {
      en: "United Arab Emirates",
      fr: "Émirats Arabes Unis",
      sp: "Emiratos Árabes Unidos",
      ge: "Vereinigte Arabische Emirate",
      de: "United Arab Emirates",
    },
    alpha3: "ARE",
    countryCode: "784",
    label: "AE - United Arab Emirates",
  },
  GB: {
    locales: {
      en: "United Kingdom of Great Britain and Northern Ireland",
      fr: "Royaume-Uni",
      sp: "Reino Unido",
      ge: "Vereinigtes Königreich",
      de: "United Kingdom",
    },
    alpha3: "GBR",
    countryCode: "826",
    label: "GB - United Kingdom of Great Britain and Northern Ireland",
  },
  UM: {
    locales: {
      en: "United States Minor Outlying Islands",
      fr: "Iles mineures éloignées des États-Unis d'Amérique",
      sp: "Islas Ultramarinas Menores de los Estados Unidos",
      ge: "Kleinere abgelegene Inseln der Vereinigten Staaten",
      de: "United States Minor Outlying Islands",
    },
    alpha3: "UMI",
    countryCode: "581",
    label: "UM - United States Minor Outlying Islands",
  },
  US: {
    locales: {
      en: "United States of America",
      fr: "États-Unis d'Amérique",
      sp: "Estados Unidos de América",
      ge: "Vereinigte Staaten von Amerika",
      de: "United States of America",
    },
    alpha3: "USA",
    countryCode: "840",
    label: "US - United States of America",
  },
  UY: {
    locales: {
      en: "Uruguay",
      fr: "Uruguay",
      sp: "Uruguay",
      ge: "Uruguay",
      de: "Uruguay",
    },
    alpha3: "URY",
    countryCode: "858",
    label: "UY - Uruguay",
  },
  UZ: {
    locales: {
      en: "Uzbekistan",
      fr: "Ouzbékistan",
      sp: "Uzbekistán",
      ge: "Usbekistan",
      de: "Uzbekistan",
    },
    alpha3: "UZB",
    countryCode: "860",
    label: "UZ - Uzbekistan",
  },
  VU: {
    locales: {
      en: "Vanuatu",
      fr: "Vanuatu",
      sp: "Vanuatu",
      ge: "Vanuatu",
      de: "Vanuatu",
    },
    alpha3: "VUT",
    countryCode: "548",
    label: "VU - Vanuatu",
  },
  VE: {
    locales: {
      en: "Venezuela (Bolivarian Republic of)",
      fr: "Vénézuela",
      sp: "Venezuela, República Bolivariana de",
      ge: "Venezuela, Bolivarische Republik",
      de: "Venezuela, Bolivarian Republic of",
    },
    alpha3: "VEN",
    countryCode: "862",
    label: "VE - Venezuela (Bolivarian Republic of)",
  },
  VN: {
    locales: {
      en: "Viet Nam",
      fr: "Vietnam",
      sp: "Vietnam",
      ge: "Viet Nam",
      de: "Viet Nam",
    },
    alpha3: "VNM",
    countryCode: "704",
    label: "VN - Viet Nam",
  },
  VG: {
    locales: {
      en: "Virgin Islands (British)",
      fr: "Iles Vierges britanniques",
      sp: "Islas Vírgenes Británicas",
      ge: "Britische Jungferninseln",
      de: "British Virgin Islands",
    },
    alpha3: "VGB",
    countryCode: "92",
    label: "VG - Virgin Islands (British)",
  },
  VI: {
    locales: {
      en: "Virgin Islands (U.S.)",
      fr: "Iles Vierges des États-Unis",
      sp: "Islas Vírgenes de EE.UU.",
      ge: "Jungferninseln der Vereinigten Staaten",
      de: "US Virgin Islands",
    },
    alpha3: "VIR",
    countryCode: "850",
    label: "VI - Virgin Islands (U.S.)",
  },
  WF: {
    locales: {
      en: "Wallis and Futuna",
      fr: "Wallis et Futuna",
      sp: "Wallis y Futuna",
      ge: "Wallis und Futuna",
      de: "Wallis and Futuna",
    },
    alpha3: "WLF",
    countryCode: "876",
    label: "WF - Wallis and Futuna",
  },
  EH: {
    locales: {
      en: "Western Sahara",
      fr: "Sahara occidental",
      sp: "Sahara Occidental",
      ge: "Westsahara",
      de: "Western Sahara",
    },
    alpha3: "ESH",
    countryCode: "732",
    label: "EH - Western Sahara",
  },
  YE: {
    locales: {
      en: "Yemen",
      fr: "Yémen",
      sp: "Yemen",
      ge: "Jemen",
      de: "Yemen",
    },
    alpha3: "YEM",
    countryCode: "887",
    label: "YE - Yemen",
  },
  ZM: {
    locales: {
      en: "Zambia",
      fr: "Zambie",
      sp: "Zambia",
      ge: "Sambia",
      de: "Zambia",
    },
    alpha3: "ZMB",
    countryCode: "894",
    label: "ZM - Zambia",
  },
  ZW: {
    locales: {
      en: "Zimbabwe",
      fr: "Zimbabwe",
      sp: "Zimbabue",
      ge: "Simbabwe",
      de: "Zimbabwe",
    },
    alpha3: "ZWE",
    countryCode: "716",
    label: "ZW - Zimbabwe",
  },
};

export const alpha2 = Object.keys(countries);
